### ISSUE TITLE
Chrome failed to start on running protractor test

### ISSUE THREAD

**Issue by zaka29** [angular/angular-phonecat#221]
Protractor fails to run with following error messages. I checked my npm server was running at localhost:8000. I had Chrome browser window popped up and then unexpectedly closed.

bdt-pc-77:angular-phonecat stan.zaichenko$ npm run protractor

> angular-phonecat@0.0.0 preprotractor /Users/stan.zaichenko/Projects/angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver /Users/stan.zaichenko/Projects/angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall /Users/stan.zaichenko/Projects/angular-phonecat
> bower install

> angular-phonecat@0.0.0 update-webdriver /Users/stan.zaichenko/Projects/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /Users/stan.zaichenko/Projects/angular-phonecat
> protractor test/protractor-conf.js

Using ChromeDriver directly...

/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:109
  var template = new Error(this.message);
                 ^
UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.10.0 x86_64)
    at new bot.Error (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
    at Object.bot.response.checkResponse (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:134:24
    at /Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1539:20)
    at notify (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:362:12)
    at notifyAll (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:331:7)
    at resolve (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:309:7)
    at fulfill (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:429:5)
    at /Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:49)
    at Function.webdriver.WebDriver.createSession (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:111:30)
    at Object.createDriver (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:460:30)
    at ChromeDriverProvider.getDriver (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/lib/driverProviders/chrome.js:67:27)
    at /Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/lib/runner.js:221:35
    at _fulfilled (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/stan.zaichenko/Projects/angular-phonecat/node_modules/protractor/node_modules/q/q.js:525:49

npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! cwd /Users/stan.zaichenko/Projects/angular-phonecat
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/stan.zaichenko/Projects/angular-phonecat/npm-debug.log
npm ERR! not ok code 0

**Comment by hilary** [comment]
@zaka29 It seems that the tutorial's npm scripts are quite sensitive to node version. I solved this problem by installing [nvm](https://github.com/creationix/nvm), installing v0.10.27 and running the npm scripts under v0.10.27.

**Comment by petebacondarwin** [comment]
I think there was a problem with 0.10.28. Other versions seem to work fine. I am on 0.12.2
