### ISSUE TITLE
bower install not working. Permission denied configstore.

### ISSUE THREAD

**Issue by Dapsang** [angular/angular-phonecat#228]
I've been browsing the various issues with `bower install` and tried different solutions such as `npm install -g bower`. I also tried cleaning the cache if there is one but still gives me the same error. I've been hours at this, I checked that I have all permissions to the `angular-phonecat` folder, I even made a `chmod -R 777` to make sure. I also completely reinstalled node and npm at least 3 times. Please help! I want to go further than step 0 of the tutorial....

I understand I'm not supposed to run `npm install` with sudo. 

The server does run but only if I do `sudo npm start`, if I do bower doesn't run and I get the following warning:

`npm WARN cannot run in wd angular-phonecat@0.0.0 bower install (wd=/Users/JLD/Dropbox/Angular JS/angular-phonecat)`

This is the output I get when I do `npm install`:

> angular-phonecat@0.0.0 postinstall /Users/JLD/Dropbox/Angular JS/angular-phonecat
> bower install

Error: EACCES, permission denied '/Users/JLD/.config/configstore'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Function.sync (/Users/JLD/Dropbox/Angular JS/angular-phonecat/node_modules/bower/node_modules/mkdirp/index.js:70:13)
    at Object.create.all.get (/Users/JLD/Dropbox/Angular JS/angular-phonecat/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:41:13)
    at Object.Configstore (/Users/JLD/Dropbox/Angular JS/angular-phonecat/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/Users/JLD/Dropbox/Angular JS/angular-phonecat/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/Users/JLD/Dropbox/Angular JS/angular-phonecat/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/Users/JLD/Dropbox/Angular JS/angular-phonecat/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/Users/JLD/Dropbox/Angular JS/angular-phonecat/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/JLD/Dropbox/Angular JS/angular-phonecat
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/JLD/Dropbox/Angular JS/angular-phonecat/npm-debug.log
npm ERR! not ok code 0

I am using macOSX mavericks. I also have the complete log and will be happy to provide it if requested. 
This is very frustrating any help or guidance would be greatly appreciated.

**Comment by Dapsang** [comment]
Ok it is now resolved. I just had to change the permissions on the .config folder. I checked and noticed that configstore doesn't exist. So It was just a permission issue directly with the .config folder and not with  the angular-phonecat folder.

**Comment by aronysidoro** [comment]
@Dapsang that was exactly my issue also. Thanks.
