### ISSUE TITLE
step-4 protractor test fails

### ISSUE THREAD

**Issue by strongliang** [angular/angular-phonecat#232]
```
Failures:

  1) PhoneCat App Phone list view should be possible to control phone order via the drop down select box
   Message:
     Expected [ 'Motorola XOOM™ with Wi-Fi
The Next, Next Generation tablet.', 'MOTOROLA XOOM™
The Next, Next Generation tablet.' ] to equal [ 'Motorola XOOM™ with Wi-Fi', 'MOTOROLA XOOM™' ].
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/zhuang/Downloads/angular-phonecat-ref/test/e2e/scenarios.js:43:26)

  2) PhoneCat App Phone list view should be possible to control phone order via the drop down select box
   Message:
     Expected [ 'MOTOROLA XOOM™
The Next, Next Generation tablet.', 'Motorola XOOM™ with Wi-Fi
The Next, Next Generation tablet.' ] to equal [ 'MOTOROLA XOOM™', 'Motorola XOOM™ with Wi-Fi' ].
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/zhuang/Downloads/angular-phonecat-ref/test/e2e/scenarios.js:50:26)

Finished in 3.867 seconds
2 tests, 5 assertions, 2 failures
```

**Comment by LadySubrosa** [comment]
This is so not okay! It's driving me crazy, and this is the only other post related to this issue I have seen.

I thought that there might have been some kind of weird syntax mismatch, but even when I copy/pasted the names as I had typed them in my controller I get this same error. I've tried manually installing chromeDriver, I've tried, updating my instance of Protractor a million times, and I just want to move on with my life onto the next part of this tutorial with a clear conscious, sober in the fact that I have practiced the ancient art of e2e correctly.

Full disclosure: I have also set my package.json dependencies for protractor to: "protractor": "*", (for the latest version, right?) and my protractor settings to "  directConnect: true,
  chromeOnly: false," because other people with similar issues did similar things.

Also, my protractor rage quits on me after it finishes the test with the following:

```
Finished in 1.993 seconds
3 tests, 7 assertions, 1 failure

[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! cwd /Users/sparkpro/Documents/Web Dev/angular-phonecat
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/sparkpro/Documents/Web Dev/angular-phonecat/npm-debug.log
npm ERR! not ok code 0
```

**Comment by gkalpak** [comment]
All dependencies and tools have been updated recently and this is hopefully not an issue any more.
If anyone is still having problems, please open a new issue.
