### ISSUE TITLE
events.js:85       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Falieson** [angular/angular-phonecat#248]
On the Tutorial Page, before Step 0, the first test of the local node server fails.

696* git clone --depth=14 https://github.com/angular/angular-phonecat.git
  697* cd angular-phonecat
  698* node --version
  699* npm install
  700* bower install
  705  npm run update-webdriver
  706  npm start

```$ npm start

> angular-phonecat@0.0.0 prestart ~/Code/Tutorials/AngularJS/angular-phonecat
> npm install


> angular-phonecat@0.0.0 postinstall ~/Code/Tutorials/AngularJS/angular-phonecat
> bower install


> angular-phonecat@0.0.0 start ~/Code/Tutorials/AngularJS/angular-phonecat
> http-server -a 0.0.0.0 -p 8000

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at net.js:1253:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server -a 0.0.0.0 -p 8000'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a 0.0.0.0 -p 8000
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:```

**Comment by lexalexander10** [comment]
EADDRINUSE usually means that the port number which listen() tries to connect to is already in use. Did you check to see if you already have a server running on port 80 already? I had a similar problem and that was the issue.

**Comment by pkozlowski-opensource** [comment]
Right, thnx for helping out @lexalexander10 !

**Comment by gameboyzone** [comment]
@pkozlowski-opensource @Falieson 

I had the same issue. Surprisingly I resolved it by closing my command prompt and opening a new one. 

Could be some environmental variables were set in the previous command which does not get picked up right away.
