### ISSUE TITLE
npm start fails in Ubuntu 14.04

### ISSUE THREAD

**Issue by tqisjim** [angular/angular-phonecat#264]
stdout:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 start script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a 0.0.0.0 -p 8000
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /home/tqis/angular-phonecat
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tqis/angular-phonecat/npm-debug.log
npm ERR! not ok code 0

npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.30
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info start angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec start script
10 error angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
10 error Exit status 8
11 error Failed at the angular-phonecat@0.0.0 start script.
11 error This is most likely a problem with the angular-phonecat package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     http-server -a 0.0.0.0 -p 8000
11 error You can get their info via:
11 error     npm owner ls angular-phonecat
11 error There is likely additional logging output above.
12 error System Linux 3.13.0-57-generic
13 error command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error cwd /home/tqis/angular-phonecat
15 error node -v v0.10.30
16 error npm -v 1.4.21
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

Sorry if I overlooked something obvious.

**Comment by tqisjim** [comment]
works great using the Ubuntu packages:  npm v1.3.10 ; node v0.10.25
