### ISSUE TITLE
npm run protractor fail on Mac OS 10.11.1, throwing error "Server terminated early with status 1"

### ISSUE THREAD

**Issue by AnfernyQiu** [angular/angular-phonecat#285]
Hello everyone:

I'm going to study the tutorial of angular-phonecat, when running "npm run protractor",
#####  prompt a window like this:
<img width="416" alt="screen shot 2015-11-19 at 9 53 55 am" src="https://cloud.githubusercontent.com/assets/14922660/11260174/9ab7760a-8ea3-11e5-9a21-dff90e3f95d9.png">
##### error message is below:
> angular-phonecat@0.0.0 preprotractor /Users/Qiurunbai/Documents/angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver /Users/Qiurunbai/Documents/angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall /Users/Qiurunbai/Documents/angular-phonecat
> bower install

> angular-phonecat@0.0.0 update-webdriver /Users/Qiurunbai/Documents/angular-phonecat
> webdriver-manager update
selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /Users/Qiurunbai/Documents/angular-phonecat
> protractor test/protractor-conf.js
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/Users/Qiurunbai/Documents/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^

>Error: Server terminated early with status 1
    at Error (native)
    at /Users/Qiurunbai/Documents/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:206:18
    at promise.Promise.goog.defineClass.invokeCallback_ (/Users/Qiurunbai/Documents/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/Users/Qiurunbai/Documents/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/Users/Qiurunbai/Documents/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/Users/Qiurunbai/Documents/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:366:9)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Qiurunbai/Documents/angular-phonecat/npm-debug.log

##### Debug log below:
>0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:818:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd /Users/Qiurunbai/Documents/angular-phonecat
13 error Darwin 15.0.0
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
15 error node v4.2.1
16 error npm  v2.14.7
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor test/protractor-conf.js
19 error You can get their info via:
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

#### I've tried these:
1.install latest Java;
2.run "sudo npm install protractor"
3.run "protractor test/protractor-conf.js"
But it didn't work.

**Comment by AnfernyQiu** [comment]
install java by these commands will resolve the problem:
brew update
brew cask java
