### ISSUE TITLE
[Step 3] Protractor test fails on browser.getTitle() assertion

### ISSUE THREAD

**Issue by thorne51** [angular/angular-phonecat#300]
Have searched around and can't get this test to pass. In the browser window opened by Selenium I can see that the title is not updating, either using ng-bind-template or just putting the expression directly in the <title> tag.

Manually testing this in Chrome it works perfectly but the protractor test still fails. Any suggestions?

**Comment by seaward** [comment]
Same issue here. I found the title is so long, so when "query.sendKeys('nexus');", only a small left part of 'n' can be seen in title. 
Error message as below:
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
.F

Failures:

  1) PhoneCat App Phone list view should display the current filter value in the title bar
   Message:
     ReferenceError: query is not defined
   Stacktrace:
     ReferenceError: query is not defined
    at [object Object].<anonymous> (D:\git\repo\angular-phonecat\test\e2e\scenarios.js:30:7)
    at D:\git\repo\angular-phonecat\node_modules\jasminewd\index.js:94:14
    at goog.async.run.processWorkQueue (D:\git\repo\angular-phonecat\node_modules\selenium-webdriver\lib\goog\async\run.
js:130:15)
From: Task: Asynchronous test function: it()
    at [object Object].<anonymous> (D:\git\repo\angular-phonecat\node_modules\jasminewd\index.js:93:33)
    at [object Object].<anonymous> (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\async-callback.js:45:3
7)
    at [object Object].jasmine.Block.execute (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.
1.js:1174:17)
    at [object Object].jasmine.Queue.next_ (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.1.
js:2209:31)
    at [object Object]._onTimeout (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2199:1
8)
Error
    at [object Object].<anonymous> (D:\git\repo\angular-phonecat\test\e2e\scenarios.js:29:5)
    at [object Object].jasmine.Env.describe_ (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.
1.js:913:21)
    at [object Object].jasmine.Env.describe (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.1
.js:898:15)
    at describe (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
    at [object Object].<anonymous> (D:\git\repo\angular-phonecat\test\e2e\scenarios.js:7:3)
    at [object Object].jasmine.Env.describe_ (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.
1.js:913:21)
    at [object Object].jasmine.Env.describe (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.1
.js:898:15)
    at describe (D:\git\repo\angular-phonecat\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
    at Object.<anonymous> (D:\git\repo\angular-phonecat\test\e2e\scenarios.js:5:1)

Finished in 4.303 seconds
2 tests, 4 assertions, 1 failure

**Comment by seaward** [comment]
I found the title is so long that when send 'nexus' to 'query', only small left part of 'n' can be seen.
I run into "**ReferenceError: query is not defined**" first, but fixed by add `var query = element(by.model('query'));`

The original scenarios.js has an `it(...` in it, if I put new `it` into this block, the test will result in ** Error: jasmine.Suite() required**

**Comment by gkalpak** [comment]
There doesn't seem to be any `browser.getTitle()` in the code.
Where do you see it.

**Comment by gkalpak** [comment]
Obsolete. Closing.
