### ISSUE TITLE
Inconsistency in protractor test results

### ISSUE THREAD

**Issue by ElliotPsyIT** [angular/angular-phonecat#340]
I'm seeing that running e2e tests sometimes work through successfully and sometimes not.  

The phonecat app itself installed with no problem, and is running fine, as are the unit tests.  

I'm thinking that my hardware isn't quite up to the task, and hope someone can confirm or weigh in.  Here's what hardware I have to work with, and its configuration:

iMac 3.2 GHz Core i3, 4GB DDR3
OSX 10.9.5
node v5.0.0
npm v3.3.6

In any case, here are the results of two separate runs, the first unsuccessful and the second successful:

Unsuccessful - though I know this is an incorrect test result since I can manually work through the scenario and confirm the test assertion:
```
[11:05:38] I/local - Starting selenium standalone server...
[11:05:38] I/launcher - Running 1 instances of WebDriver
[11:05:45] I/local - Selenium standalone server started at http://10.1.10.10:57860/wd/hub
Started
.F.....

Failures:
1) PhoneCat Application View: Phone list should filter the phone list as a user types into the search box
  Message:
    Expected 20 to be 1.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/ElliotFielstein/Angular/angular-phonecat/e2e-tests/scenarios.js:26:33)
        at /Users/ElliotFielstein/Angular/angular-phonecat/node_modules/jasminewd2/index.js:96:23
        at new Promise (/Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:1043:7)
        at controlFlowExecute (/Users/ElliotFielstein/Angular/angular-phonecat/node_modules/jasminewd2/index.js:82:18)
        at TaskQueue.execute_ (/Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2697:25
        at /Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:377:9)

7 specs, 1 failure
Finished in 20.503 seconds
[11:06:42] I/local - Shutting down selenium standalone server.
[11:06:42] I/launcher - 0 instance(s) of WebDriver still running
[11:06:42] I/launcher - chrome #01 failed 1 test(s)
[11:06:42] I/launcher - overall: 1 failed spec(s)
[11:06:42] E/launcher - Process exited with error code 1
```
Successful, which confirms the falsely unsuccessful result above:
```
[11:13:44] I/local - Starting selenium standalone server...
[11:13:44] I/launcher - Running 1 instances of WebDriver
[11:13:48] I/local - Selenium standalone server started at http://10.1.10.10:57775/wd/hub
Started
.......


7 specs, 0 failures
Finished in 17.252 seconds
[11:14:33] I/local - Shutting down selenium standalone server.
[11:14:33] I/launcher - 0 instance(s) of WebDriver still running
[11:14:33] I/launcher - chrome #01 passed
```
Anyone can confirm that hardware is the culprit, or might there be another issue here?

Thanks!

**Comment by gkalpak** [comment]
I haven't seen it, but I doubt it would be hardware-related.

I would check for outdated dependencies (e.g. remove `node_modules/` and run `npm install` again) or an out-of-date Selenium Standalone Server. You can also bypass Selemium altogether by adding `directConnect: true` to your protractor config (currently in `e2e-tests/protractor.conf.js`).

BTW, in case you haven't noticed, the tutorial has been updated recently (yesterday), so you might be using the older version. If that is the case, I recommend starting over with the new version (including re-cloning the angular-phonecat repo (`git clone --depth=16 https://github.com/angular/angular-phonecat.git`) and doing a hard-refresh on https://docs.angularjs.org/tutorial to make sure you have the latest content).

--
Closing since this isn't actionable at the moment, but feel free to continue the discussion below or re-open if you find out this is soething we can fix on our side).

**Comment by ElliotPsyIT** [comment]
Thanks for the insights @gkalpak!  A few quick comments and then I'll explore your suggestions further.

As it happens, I fully installed today.  So if the update was yesterday, I think I'm covered with the latest content.  And, as mentioned, the install went without a hitch.

On the Selenium server, your suggestion to add a `directConnect: true` property to protractor's config sounds promising.  Makes me wonder if maybe there's a timing issue.  I'll let you know if that approach bears fruit.

Many thanks for the specific and timely response!!

**Comment by ElliotPsyIT** [comment]
@gkalpak, Unfortunately adding `directConnect : true` did not resolve the issue.  

I should mention that I went through the entire phonecat tutorial, running unit tests and protractor test for each step.  I ran the protractor tests either adding or not adding `directConnect`.  The result was Intermittent failure - typically first run of a step - which then resolved to passing when the test was immediately run again.  It didn't seem to matter if `directConnect` was set.  I couldn't predict which run would produce the error.  

He's another example of the sequence.  You see the first run caused an error - precisely the same error (at step-14) as my initial example above.  You see 'Using ChromeDriver directly...' which confirms `directConnect` was set:
```
> angular-phonecat@0.0.0 protractor /Users/ElliotFielstein/Angular/angular-phonecat
> protractor e2e-tests/protractor.conf.js

[13:25:03] I/direct - Using ChromeDriver directly...
[13:25:03] I/launcher - Running 1 instances of WebDriver
Started
.F.....

Failures:
1) PhoneCat Application View: Phone list should filter the phone list as a user types into the search box
  Message:
    Expected 20 to be 8.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/ElliotFielstein/Angular/angular-phonecat/e2e-tests/scenarios.js:30:33)
        at /Users/ElliotFielstein/Angular/angular-phonecat/node_modules/jasminewd2/index.js:96:23
        at new Promise (/Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:1043:7)
        at controlFlowExecute (/Users/ElliotFielstein/Angular/angular-phonecat/node_modules/jasminewd2/index.js:82:18)
        at TaskQueue.execute_ (/Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2697:25
        at /Users/ElliotFielstein/Angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:377:9)

7 specs, 1 failure
Finished in 20.027 seconds
[13:25:47] I/launcher - 0 instance(s) of WebDriver still running
[13:25:47] I/launcher - chrome #01 failed 1 test(s)
[13:25:47] I/launcher - overall: 1 failed spec(s)
[13:25:47] E/launcher - Process exited with error code 1
```
Then, I simply ran protractor tests again.  Error free:
```
 angular-phonecat@0.0.0 protractor /Users/ElliotFielstein/Angular/angular-phonecat
> protractor e2e-tests/protractor.conf.js

[13:26:33] I/direct - Using ChromeDriver directly...
[13:26:33] I/launcher - Running 1 instances of WebDriver
Started
.......


7 specs, 0 failures
Finished in 14.125 seconds
[13:26:51] I/launcher - 0 instance(s) of WebDriver still running
[13:26:51] I/launcher - chrome #01 passed
```
I've run the protractor tests a few more times in the same terminal session, each time without error.  I started a new terminal session and ran the protractor tests without error.

I just can't seem to find conditions to intentionally repeat the failing test.  May be something about my system or system configuration, but I'm not sure where to look or begin exploring?

**Comment by gkalpak** [comment]
I'm out of ideas :disappointed: 
(I might try modifying the test, adding a delay to see if it's a timing issue or something else (e.g. input fields are totally ignored) - although I'm not sure what I would do after that :smiley:
