### ISSUE TITLE
Issue with Run Protrator Script

### ISSUE THREAD

**Issue by cheenamalhotra** [angular/angular-phonecat#360]
Hi Team,

I am not able to execute "npm run protrator" from angular phonecat project, cloned in my machine. I am running **node version v4.4.3 with npm version v3.10.7**

Below is the log trace from **npm-debug.log**:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\cmalhotra\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.7
3 info using node@v4.4.3
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: C:\Users\cmalhotra\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\Learnings\Angular JS\Phonecat App\angular-phonecat\node_modules\.bin;C:\oraclexe\app\oracle\product\10.2.0\server\bin;E:\app\OracleAdmin\product\12.1.0\dbhome_1\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\iis express\PHP\v5.4;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;E:\Oracle\Middleware\jdeveloper\ant\bin;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Users\cmalhotra\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Users\cmalhotra\AppData\Local\Code\bin;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;E:\Git\cmd;E:\Dart\dart-sdk\bin;C:\Users\cmalhotra\.dnx\bin;C:\Users\cmalhotra\AppData\Roaming\npm;E:\Android\sdk\platform-tools;E:\Android\sdk\tools
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: E:\Learnings\Angular JS\Phonecat App\angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '/d /s /c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: C:\Users\cmalhotra\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\Learnings\Angular JS\Phonecat App\angular-phonecat\node_modules\.bin;C:\oraclexe\app\oracle\product\10.2.0\server\bin;E:\app\OracleAdmin\product\12.1.0\dbhome_1\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\iis express\PHP\v5.4;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;E:\Oracle\Middleware\jdeveloper\ant\bin;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Users\cmalhotra\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Users\cmalhotra\AppData\Local\Code\bin;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;E:\Git\cmd;E:\Dart\dart-sdk\bin;C:\Users\cmalhotra\.dnx\bin;C:\Users\cmalhotra\AppData\Roaming\npm;E:\Android\sdk\platform-tools;E:\Android\sdk\tools
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: E:\Learnings\Angular JS\Phonecat App\angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '/d /s /c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 1  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\cmalhotra\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at EventEmitter.emit (events.js:172:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\cmalhotra\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at ChildProcess.emit (events.js:172:7)
18 verbose stack     at maybeClose (internal/child_process.js:827:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd E:\Learnings\Angular JS\Phonecat App\angular-phonecat
21 error Windows_NT 6.1.7601
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cmalhotra\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
23 error node v4.4.3
24 error npm  v3.10.7
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 1
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by gkalpak** [comment]
It is really difficult to investigate with such a generic error message.
Have you started the webserver (using `npm start`) in a different cmd window before running `npm run protractor`?

**Comment by philnash** [comment]
Hello, I am getting a similar log and error running the protractor tests too.

The error is:

```
/Users/philnash/projects/angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^

Error: Server terminated early with status 1
    at Error (native)
    at /Users/philnash/projects/angular/angular-phonecat/node_modules/selenium-webdriver/remote/index.js:210:20
    at Promise.invokeCallback_ (/Users/philnash/projects/angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/Users/philnash/projects/angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/Users/philnash/projects/angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at asyncRun (/Users/philnash/projects/angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2652:27)
    at /Users/philnash/projects/angular/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The npm-debug.log is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/philnash/.nvm/versions/node/v6.4.0/bin/node',
1 verbose cli   '/Users/philnash/.nvm/versions/node/v6.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /Users/philnash/.nvm/versions/node/v6.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/philnash/projects/angular/angular-phonecat/node_modules/.bin:/Users/philnash/.nvm/versions/node/v6.4.0/bin:/Users/philnash/.nvm/versions/node/v6.4.0/bin:/usr/local/heroku/bin:./.bundle/bin:/Users/philnash/.rbenv/shims:/Users/philnash/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/local/share/npm/bin
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /Users/philnash/projects/angular/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /Users/philnash/.nvm/versions/node/v6.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/philnash/projects/angular/angular-phonecat/node_modules/.bin:/Users/philnash/.nvm/versions/node/v6.4.0/bin:/Users/philnash/.nvm/versions/node/v6.4.0/bin:/usr/local/heroku/bin:./.bundle/bin:/Users/philnash/.rbenv/shims:/Users/philnash/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/local/share/npm/bin
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /Users/philnash/projects/angular/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 1  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/Users/philnash/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/Users/philnash/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:852:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /Users/philnash/projects/angular/angular-phonecat
21 error Darwin 14.5.0
22 error argv "/Users/philnash/.nvm/versions/node/v6.4.0/bin/node" "/Users/philnash/.nvm/versions/node/v6.4.0/bin/npm" "run" "protractor"
23 error node v6.4.0
24 error npm  v3.10.3
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 1
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by GorgonsMaze** [comment]
I'm getting the same error at this point in the tutorial. 

I'm able to run the cmd `npm install` before opening a new terminal window.

![Image](http://i.imgur.com/wlg2maM.png)

I'm running  **node v4.6.0** and **npm  v3.10.8**

When I open a new terminal and run the  `npm run protractor` command I get chrome to open a new window with a blank screen with a url `data;`

![Image](http://i.imgur.com/LWRMLRf.png)

 get the following error message in terminal & **npm-debug-log**


```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.8
3 info using node@v4.6.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/username/angular-phonecat/node_modules/.bin:/Users/username/.rvm/gems/ruby-2.3.0/bin:/Users/username/.rvm/gems/ruby-2.3.0@global/bin:/Users/username/.rvm/rubies/ruby-2.3.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/bin:/sbin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/username/.rvm/bin
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /Users/username/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/username/angular-phonecat/node_modules/.bin:/Users/username/.rvm/gems/ruby-2.3.0/bin:/Users/username/.rvm/gems/ruby-2.3.0@global/bin:/Users/username/.rvm/rubies/ruby-2.3.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/bin:/sbin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/username/.rvm/bin
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /Users/username/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 1  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at EventEmitter.emit (events.js:172:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at ChildProcess.emit (events.js:172:7)
18 verbose stack     at maybeClose (internal/child_process.js:829:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /Users/username/angular-phonecat
21 error Darwin 15.6.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
23 error node v4.6.0
24 error npm  v3.10.8
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 1
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by gkalpak** [comment]
This sounds more related to selenium or protractor rather than the tutorial itself. Can you try adding `directConnect: true` in `e2e-tests/protractor.conf.js` and see if that helps?

**Comment by GorgonsMaze** [comment]
@gkalpak Thanks for the response. I was able to resolved the issue by running `webdriver-manager update`. Then in my **protractor.conf.js**  adding

```
  seleniumAddress: 'http://localhost:4444/wd/hub',
```
and then run `npm start`. Then in another terminal run `webdriver-manager start`, then open 3rd terminal and run `npm run protractor`. Everything works perfect now.

**Comment by gkalpak** [comment]
OK, thx for getting back. Since we haven't heard from the OP and you were able to resolve your issue let's close this. Protractor should be able to handle all that for you under the hood, so no idea why it couldn't in your case, but it doesn't seem related to the tutorial itself 😕
