### ISSUE TITLE
Failing e2e tests

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [angular/angular-phonecat#377]
Following https://docs.angularjs.org/tutorial/#environment-setup
I ran application in a terminal with `npm start`, then in another tab, `npm run protractor` which failed.

Here's the error log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/dev/.nvm/versions/node/v6.8.1/bin/node',
1 verbose cli   '/home/dev/.nvm/versions/node/v6.8.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.9
3 info using node@v6.8.1
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /home/dev/.nvm/versions/node/v6.8.1/lib/node_modules/npm/bin/node-gyp-bin:/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/.bin:/home/dev/.nvm/versions/node/v6.8.1/bin:/home/dev/bin:/home/dev/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /home/dev/code/angularjs/tutorials/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /home/dev/.nvm/versions/node/v6.8.1/lib/node_modules/npm/bin/node-gyp-bin:/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/.bin:/home/dev/.nvm/versions/node/v6.8.1/bin:/home/dev/bin:/home/dev/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /home/dev/code/angularjs/tutorials/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 1  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/home/dev/.nvm/versions/node/v6.8.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/home/dev/.nvm/versions/node/v6.8.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:877:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /home/dev/code/angularjs/tutorials/angular-phonecat
21 error Linux 4.4.0-43-generic
22 error argv "/home/dev/.nvm/versions/node/v6.8.1/bin/node" "/home/dev/.nvm/versions/node/v6.8.1/bin/npm" "run" "protractor"
23 error node v6.8.1
24 error npm  v3.10.9
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 1
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

Node and NPM versions are on 23rd and 24th line above.

**Comment by IAmAnubhavSaini** [comment]
Then I installed jre and jdk via `sudo apt install default-jre default-jdk` and ran `npm run protrator` again. Found this error:

```
npm run protractor

> angular-phonecat@0.0.0 preprotractor /home/dev/code/angularjs/tutorials/angular-phonecat
> npm run update-webdriver


> angular-phonecat@0.0.0 preupdate-webdriver /home/dev/code/angularjs/tutorials/angular-phonecat
> npm install


> angular-phonecat@0.0.0 postinstall /home/dev/code/angularjs/tutorials/angular-phonecat
> bower install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> angular-phonecat@0.0.0 update-webdriver /home/dev/code/angularjs/tutorials/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /home/dev/code/angularjs/tutorials/angular-phonecat
> protractor e2e-tests/protractor.conf.js

[09:22:55] I/local - Starting selenium standalone server...
[09:22:55] I/launcher - Running 1 instances of WebDriver
[09:22:55] I/local - Selenium standalone server started at http://10.0.2.15:50148/wd/hub

/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/error.js:27
    super(opt_error);
    ^
SessionNotCreatedError: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"24588.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.59)
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.4.0-43-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.07 seconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'dev-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-43-generic', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at WebDriverError (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/error.js:27:5)
    at SessionNotCreatedError (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/error.js:296:5)
    at Object.checkLegacyResponse (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/error.js:580:13)
    at /home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/lib/webdriver.js:64:13
    at Promise.invokeCallback_ (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at asyncRun (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2652:27)
    at /home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at acquireSession (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
    at Builder.build (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/selenium-webdriver/builder.js:458:24)
    at Local.DriverProvider.getNewDriver (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/protractor/built/runner.js:182:43)
    at /home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/protractor/built/runner.js:255:30
    at _fulfilled (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/q/q.js:796:13)
    at /home/dev/code/angularjs/tutorials/angular-phonecat/node_modules/q/q.js:604:44
[09:22:57] E/launcher - Process exited with error code 1

npm ERR! Linux 4.4.0-43-generic
npm ERR! argv "/home/dev/.nvm/versions/node/v6.8.1/bin/node" "/home/dev/.nvm/versions/node/v6.8.1/bin/npm" "run" "protractor"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/dev/code/angularjs/tutorials/angular-phonecat/npm-debug.log
```

**Comment by IAmAnubhavSaini** [comment]
```
dev@dev-VirtualBox:~/code/angularjs/tutorials/angular-phonecat$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
dev@dev-VirtualBox:~/code/angularjs/tutorials/angular-phonecat$ npm -v
3.10.9
dev@dev-VirtualBox:~/code/angularjs/tutorials/angular-phonecat$ node -v
v6.8.1
```

**Comment by hesterrocks** [comment]
I had the same errors when run ### npm run protrator

**Comment by hesterrocks** [comment]
I had the same errors when I ran ### npm run protrator

**Comment by hesterrocks** [comment]
I had the same errors when I ran `npm run protrator`

**Comment by petebacondarwin** [comment]
I am not sure we have tested this on node 6 - could you try node 4?

**Comment by gkalpak** [comment]
FWIW, it works for me (on Windows) with node v6.8.1 :confused:

**Comment by Narretz** [comment]
node 4.4.4
npm 2.15.1
Java RE build 1.8.0_101-b13

npm packages shouldn't be a variable, as we all install the same. But you can try by installing a newer  (>3) protractor version for example.

**Comment by gkalpak** [comment]
There seems to be an issue on linux (I tried on Ubuntu 16.04).
Updating protractor to version 4.0.9 solves the issue. (I'll submit a fix.)

**Comment by IAmAnubhavSaini** [comment]
Thanks @gkalpak
