### ISSUE TITLE
Error while running protractor conf.js

### ISSUE THREAD

**Issue by kvaranasi80** [angular/angular-phonecat#380]
Hi When I am running the above command to test the example. 
I am getting the following error. 
[13:34:35] I/direct - Using ChromeDriver directly...
[13:34:35] I/launcher - Running 1 instances of WebDriver
[13:34:38] E/launcher - spawn UNKNOWN
[13:34:38] E/launcher - Error: spawn UNKNOWN
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:362:9)
    at exec (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\io\exec.js:123:27)
    at C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\remote\index.js:206:23
    at ManagedPromise.invokeCallback_ (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25
    at C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
    at Driver (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:778:38)
    at Direct.getNewDriver (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\direct.js:68:26)
    at Runner.createBrowser (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\built\runner.js:198:43)
    at C:\Users\*\AppData\Roaming\npm\node_modules\protractor\built\runner.js:277:30
    at _fulfilled (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\*\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[13:34:38] E/launcher - Process exited with error code 199

I am using the following versions 

C:\Users\*\AppData\Roaming\npm>node --version
v4.4.3

C:\Users\*\AppData\Roaming\npm>protractor --version
Version 4.0.9

C:\Users\*\AppData\Roaming\npm>

**Comment by gkalpak** [comment]
What is the local version of protractor that you are using (not the globally installed one)?

**Comment by kvaranasi80** [comment]
I am using 2.5.1, I downgraded protractor version as I was having this issue with the latest protractor version

**Comment by gkalpak** [comment]
OK, can't help you much more then :smiley:
Feel free to open another issue if you are run into more problems.
