### ISSUE TITLE
Issues while running npm run protractor - Timed out waiting for the WebDriver server...

### ISSUE THREAD

**Issue by pranabkd** [angular/angular-phonecat#384]
As per the error on the console the following fails in my system:

protractor e2e-tests/protractor.conf.js

Complete log:
=========

Pranab@Pranab MINGW64 ~/angular-phonecat (master)
$ npm run protractor

> angular-phonecat@0.0.0 preprotractor C:\Users\Pranab\angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver C:\Users\Pranab\angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall C:\Users\Pranab\angular-phonecat
> bower install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

> angular-phonecat@0.0.0 update-webdriver C:\Users\Pranab\angular-phonecat
> webdriver-manager update

[19:16:21] I/file_manager - creating folder C:\Users\Pranab\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium
[19:16:21] I/downloader - selenium standalone: downloading version 2.53.1
[19:16:21] I/downloader - curl -o C:\Users\Pranab\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
[19:16:21] I/downloader - chromedriver: downloading version 2.25
[19:16:21] I/downloader - curl -o C:\Users\Pranab\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_2.25win32.zip https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
[19:16:21] I/downloader - geckodriver: downloading version v0.11.1
[19:16:21] I/downloader - curl -o C:\Users\Pranab\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium/geckodriver-v0.11.1-win64.zip https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-win64.zip
[19:16:25] I/update - chromedriver: unzipping C:\Users\Pranab\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.25win32.zip
[19:17:58] I/update - geckodriver: unzipping C:\Users\Pranab\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.11.1-win64.zip

> angular-phonecat@0.0.0 protractor C:\Users\Pranab\angular-phonecat
> protractor e2e-tests/protractor.conf.js

[19:17:59] I/local - Starting selenium standalone server...
[19:17:59] I/launcher - Running 1 instances of WebDriver
[19:18:39] E/launcher - Timed out waiting for the WebDriver server at http://100.113.127.144:62412/wd/hub
[19:18:39] E/launcher - Error: Timed out waiting for the WebDriver server at http://100.113.127.144:62412/wd/hub
    at Error (native)
    at onError (C:\Users\Pranab\angular-phonecat\node_modules\selenium-webdriver\http\util.js:87:11)
    at ManagedPromise.invokeCallback_ (C:\Users\Pranab\angular-phonecat\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\Pranab\angular-phonecat\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\Pranab\angular-phonecat\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (C:\Users\Pranab\angular-phonecat\node_modules\selenium-webdriver\lib\promise.js:2775:27)
    at C:\Users\Pranab\angular-phonecat\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
[19:18:39] E/launcher - Process exited with error code 199

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Pranab\angular-phonecat\npm-debug.log

**Comment by gkalpak** [comment]
What versions of Protractor and Node are you using?
FWIW, it works for me with the same version of Selenium/ChromeDriver with Protractor v4.0.11 (on Windows 10).

**Comment by bharathkallurs** [comment]
Please check if java (JRE) is installed in your system. In my case it turned out that I had got a new system with ubuntu 16.04 and jre was not present. Make sure that the java path is accessible to selenium server started by protractor. 

Also open 2 CLI windows and in the first run `npm start` and in another run `npm run protractor`

**Comment by gkalpak** [comment]
Closing since we haven't heard back from the OP and there is no indication that the issue is directly related to `angular-phonecat`.
