### ISSUE TITLE
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/p rotractor.conf.js'.

### ISSUE THREAD

**Issue by hoangdangninh** [angular/angular-phonecat#388]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'protractor' ]
2 info using npm@3.10.7
3 info using node@v6.6.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/hd/Documents/GitHub/angular-phonecat/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /home/hd/Documents/GitHub/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/hd/Documents/GitHub/angular-phonecat/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /home/hd/Documents/GitHub/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 1  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:877:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /home/hd/Documents/GitHub/angular-phonecat
21 error Linux 4.4.0-53-generic
22 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "protractor"
23 error node v6.6.0
24 error npm  v3.10.7
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 1
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by gkalpak** [comment]
Unfortunately there is not enough info here diagnose what the problem might be. Everything seems as expected as far as angular-phonecat is concerned. I suggest you open an issue on the protractor repo (unless there already a similar issue reported).
