### ISSUE TITLE
Failing installation at bower angular-mocks#1.5.x

### ISSUE THREAD

**Issue by Mohakjuneja** [angular/angular-phonecat#391]
I'm installing the application on Mac OS Sierra and I can't seem to get rid of the problem.
I've attached the trace for your reference.

Stack trace:
Error: EACCES: permission denied, rename '/var/folders/xl/6hgnfkld1zs4zxtyqw2bsm6c0000gn/T/mojojojo/bower/f6200e65f802695e672eba66b582c642-67011-uIHXnG' -> '/Users/mojojojo/.cache/bower/packages/ca4abf9feb8e8cf7b0d2475ad1033dc3/1.5.10'

Console trace:
Error
    at StandardRenderer.error (/Users/mojojojo/Documents/angular/angular-phonecat/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/Users/mojojojo/Documents/angular/angular-phonecat/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/Users/mojojojo/Documents/angular/angular-phonecat/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/mojojojo/Documents/angular/angular-phonecat/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/Users/mojojojo/Documents/angular/angular-phonecat/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /Users/mojojojo/Documents/angular/angular-phonecat/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/Users/mojojojo/Documents/angular/angular-phonecat/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/mojojojo/Documents/angular/angular-phonecat/node_modules/bower/lib/node_modules/q/q.js:788:41)

**Comment by gkalpak** [comment]
This is a bower error (probably related to permissions on your system) - not directly related to `angular-phonecat`. There are several resources for troubleshooting online. [This thread][1] has some useful suggestions you might want to try (although I would only go for `sudo` as a last resort).

[1]: http://stackoverflow.com/questions/22257726/eacces-error-with-bower-install
