### ISSUE TITLE
error of npm run protractor

### ISSUE THREAD

**Issue by lazyManLearn** [angular/angular-phonecat#401]
[22:17:08] I/local - Starting selenium standalone server...
[22:17:08] I/launcher - Running 1 instances of WebDriver
[22:17:08] E/launcher - spawn java ENOENT
[22:17:08] E/launcher - Error: spawn java ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
[22:17:08] E/launcher - Process exited with error code 199

**Comment by gkalpak** [comment]
Do you have Java installed and on the PATH?

**Comment by lazyManLearn** [comment]
Sorry, I am the beginer of Angular and I have to commit the fact that I do not know too much about this . Actually, I am a Chinese  and my English is not pretty good .

**Comment by gkalpak** [comment]
This is not related to AngularJS. Do you have Java installed on your machine?

**Comment by lazyManLearn** [comment]
Sorry, I did not install Java .I had only installed PhP for it .will it influence this project ?

**Comment by gkalpak** [comment]
In order to use this project, make sure you follow the instructions in the [tutorial][1].
There you can find detailed info about what you need to install on your machine and how to do it.

Closing, since this is not actionable. 

##
BTW, for general support questions you can ask for help on one of the [support channels][2].

[1]: https://docs.angularjs.org/tutorial
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by lazyManLearn** [comment]
Thank you very much.I will look the guidance booklet carefully when I go back.
