### ISSUE TITLE
This fails in my system: http-server ./app -a localhost -p 8000 -c-1

### ISSUE THREAD

**Issue by DharmaSamurai** [angular/angular-phonecat#402]
I have Linux Ubuntu 16.04 LTS 64bit
I do:
**npm start**

> angular-phonecat@0.0.0 prestart /home/satori/Angular/angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall /home/satori/Angular/angular-phonecat
> bower install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> angular-phonecat@0.0.0 start /home/satori/Angular/angular-phonecat
> http-server ./app -a localhost -p 8000 -c-1

events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1028:11)
    at exports._exceptionWithHostPort (util.js:1051:20)
    at Server._listen2 (net.js:1261:14)
    at listen (net.js:1297:10)
    at doListening (net.js:1396:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Linux 4.8.0-39-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server ./app -a localhost -p 8000 -c-1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server ./app -a localhost -p 8000 -c-1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server ./app -a localhost -p 8000 -c-1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/satori/Angular/angular-phonecat/npm-debug.log

**Comment by DharmaSamurai** [comment]
I just fixed it:

Последняя версия ноды
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

Делаем символьную ссылку на последнюю версию
ln -s /usr/local/n/versions/node/7.6.0/bin/node /usr/bin/node

Убиваем процесс занимающий порт 8000
fuser -vn tcp 8000
kill -9 1830
