### ISSUE TITLE
Geeting below error while doing npm start in Windows 10 Enterprise OS

### ISSUE THREAD

**Issue by SanthoshPK** [angular/angular-phonecat#406]
@marcenuc  @mprobst  @fuentesjr @smith @evmar 
Please help me what am in doing wrong here . .

C:\Users\santhosh.z.kumar\Documents\Personal\Demo\angular-phonecat>npm start

> angular-phonecat@0.0.0 prestart C:\Users\santhosh.z.kumar\Documents\Personal\Demo\angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall C:\Users\santhosh.z.kumar\Documents\Personal\Demo\angular-phonecat
> bower install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

> angular-phonecat@0.0.0 start C:\Users\santhosh.z.kumar\Documents\Personal\Demo\angular-phonecat
> http-server ./app -a localhost -p 8000 -c-1

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server ./app -a localhost -p 8000 -c-1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server ./app -a localhost -p 8000 -c-1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server ./app -a localhost -p 8000 -c-1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\santhosh.z.kumar\Documents\Personal\Demo\angular-phonecat\npm-debug.log

C:\Users\santhosh.z.kumar\Documents\Personal\Demo\angular-phonecat>

**Comment by SanthoshPK** [comment]
got solution from **problem with npm start #351** will close this . thank you.
