### ISSUE TITLE
npm run protractor fail

### ISSUE THREAD

**Issue by RichardWSD** [angular/angular-phonecat#407]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Open_Source_Project\angular-phonecat\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\app\deng\product\11.1.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Python27;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Program Files\Java\jdk1.8.0_121\jre\bin;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\deng\.windows-build-tools\python27;C:\Users\deng\AppData\Local\Yarn\.bin;C:\Users\deng\AppData\Roaming\npm
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: D:\Open_Source_Project\angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '/d /s /c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 1  signal: null
11 info lifecycle angular-phonecat@0.0.0~preprotractor: Failed to exec preprotractor script
12 verbose stack Error: angular-phonecat@0.0.0 preprotractor: `npm run update-webdriver`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid angular-phonecat@0.0.0
14 verbose cwd D:\Open_Source_Project\angular-phonecat
15 error Windows_NT 6.1.7601
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
17 error node v6.9.5
18 error npm  v3.10.10
19 error code ELIFECYCLE
20 error angular-phonecat@0.0.0 preprotractor: `npm run update-webdriver`
20 error Exit status 1
21 error Failed at the angular-phonecat@0.0.0 preprotractor script 'npm run update-webdriver'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the angular-phonecat package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run update-webdriver
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs angular-phonecat
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls angular-phonecat
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

node version : v6.9.5
npm version: 3.10.10
operation system: windows7 64 bit
I have install java

**Comment by RichardWSD** [comment]
protractor version: 4.0.14

**Comment by gkalpak** [comment]
What happens if you run `node_modules/.bin/webdriver-manager update`?

**Comment by RichardWSD** [comment]
thanks, i have solve the problem. I delete the workspace's node_modules directory and npm install again, and I install the protractor globally and then it worked.
