### ISSUE TITLE
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "sand***@***.com" with a private key was found.

### ISSUE THREAD

**Issue by raulosandeep93** [angular/angular-phonecat#433]
Hi All,

I'm trying to run my protractor script through Mac machine on iPad real device. I have started the server using **webdriver-manager start** which says 

(node:5114) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[Appium] Welcome to Appium v1.6.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

But when I'm trying to run the script using **protractor iOSConfig.ts** it is throwing the error as 

node:5118) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[15:37:20] I/launcher - Running 1 instances of WebDriver
[15:37:20] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[15:37:21] E/launcher - Error code: 135
[15:37:21] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4723
[15:37:21] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4723
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at createDriver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:635:14)
    at Hosted.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/usr/local/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
[15:37:21] E/launcher - Process exited with error code 135

**Comment by gkalpak** [comment]
Sounds like this is the wrong repo.
