### ISSUE TITLE
npm run protractor problem

### ISSUE THREAD

**Issue by km2355** [angular/angular-phonecat#436]
I failed npm run protractor,
I also added   chromeOnly:true, but it doen't work.

-----------
(node:5480) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[17:17:20] I/local - Starting selenium standalone server...
[17:17:20] I/launcher - Running 1 instances of WebDriver
[17:17:21] E/launcher - spawn java ENOENT
[17:17:21] E/launcher - Error: spawn java ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[17:17:21] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 199
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SW\AppData\Roaming\npm-cache\_logs\2018-06-29T08_17_21_104Z-debug.log

=====================================

and when I added    directConnect:true,, I had another problem,

$ npm run protractor

> angular-phonecat@0.0.0 preprotractor C:\Users\SW\angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver C:\Users\SW\angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall C:\Users\SW\angular-phonecat
> bower install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

up to date in 7.555s

> angular-phonecat@0.0.0 update-webdriver C:\Users\SW\angular-phonecat
> webdriver-manager update

[17:20:40] I/update - selenium standalone: file exists C:\Users\SW\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-2.53.1.jar
[17:20:40] I/update - selenium standalone: v2.53.1 up to date
[17:20:40] I/update - chromedriver: file exists C:\Users\SW\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.26win32.zip
[17:20:40] I/update - chromedriver: unzipping chromedriver_2.26win32.zip
[17:20:40] I/update - chromedriver: v2.26 up to date
[17:20:43] I/update - geckodriver: file exists C:\Users\SW\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.11.1-win32.zip
[17:20:43] I/update - geckodriver: unzipping geckodriver-v0.11.1-win32.zip
[17:20:45] I/update - geckodriver: vv0.11.1 up to date

> angular-phonecat@0.0.0 protractor C:\Users\SW\angular-phonecat
> protractor e2e-tests/protractor.conf.js

(node:436) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[17:20:45] I/direct - Using ChromeDriver directly...
[17:20:45] I/launcher - Running 1 instances of WebDriver
Started
FFFFFFF

==========
please help me

----------------------------------------
$ node --version
v8.11.3

**Comment by gkalpak** [comment]
The first error means that you don't have java installed (or not available on the PATH).
The second log seems to indicate that protractor worked fine, but your tests failed. (So, you have to fix the tests.)
